name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        if: success()
        run: npm run build

      - name: Test
        if: success()
        run: npm run test
